### ISSUE TITLE
Communicate with Docker Daemon to find current Digest of an image

### ISSUE THREAD

**Issue by MeneDev** [MeneDev/dockmoor#1]
dockmoor should be able to pin an image reference to the version that is currently used. For this to work, the docker daemon must be queried for the digest of the current image version.

**Comment by kai5263499** [comment]
I'd like to help but I'm having trouble figuring out how to build the project locally. Where should I start?

**Comment by MeneDev** [comment]
I've added #14. Helping should be as easy as possible, it's currently not. Thanks for pointing that out!

**Comment by MeneDev** [comment]
Does that help: https://github.com/MeneDev/dockmoor/blob/master/CONTRIBUTING.md

**Comment by kai5263499** [comment]
Thanks! What I needed to do was to 
1. setup an empty GOPATH
2. `mkdir -p src/github.com/MeneDev` 
3.  clone this repo to `src/github.com/MeneDev/dockmoor`

Not difficult but a project layout detail that took me a little bit to figure out.

Additionally, it looks like the `brew install dep` mentioned [here](https://github.com/golang/dep) is 0.5.0 which works for your project

Thanks, too, for the Visual Studio Code tip. That's what I use and that helped!

**Comment by MeneDev** [comment]
Thanks for the feedback, I'll add your steps to the description!

**Comment by MeneDev** [comment]
First draft for an interface: https://github.com/MeneDev/dockmoor/issues/8#issuecomment-431392387
